global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8081']
        labels:
          service: 'api'
    metrics_path: '/metrics'

  - job_name: 'api-service-2'
    static_configs:
      - targets: ['api-service-2:8081']
        labels:
          service: 'api'
    metrics_path: '/metrics'

  - job_name: 'worker-service'
    static_configs:
      - targets: ['worker-service:9092']
        labels:
          service: 'worker'
